# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcfcbb75f4d374e6c9f7168433b0936c07d43413fc7ec3255b81eeece324d67c2d3f8f6e1337f7201fc224bc7982a40ef69067c8e386b2c33e017a1eb2c3217c

test:
  secret_key_base: 82ed31445a1c182f59f84a01ffda2bcb7f684002aa44bb67a26bc9bf50e4d90be1f962dc41bd60b1c60d9d77e42390a04d1ecfd30a585c8fd3cd3ba6857afaf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
